$(document).ready(function(){
	
	/*--- Display information modal box ---*/
  	$(".what").click(function(){
    	$(".overlay").fadeIn(1000);

  	});

  	/*--- Hide information modal box ---*/
  	$("a.close").click(function(){
  		$(".overlay").fadeOut(1000);
  	});



// Guess Game Object
function GuessGame (currentGuess, lastGuess,randNum){

  this.currentGuess = currentGuess;
  this.lastGuess = lastGuess;
  this.randNum = randNum;
  
  
    
  var currentResult = Math.abs(this.currentGuess - this.randNum);
  var lastResult = Math.abs(this.lastGuess - this.randNum);  
console.log("The Last Guess is :" + lastGuess);
console.log("The current result is " + currentResult);
console.log("The last result is " + lastResult);
console.log("The Current Guess is : " + currentGuess);

// Get result method  
  this.getResult = function (){
    if ( currentResult == 0 ) {
    	return 0;
     } else if (lastGuess == null) {
            if (currentResult > 10) {
				return 10;            
            } else {
				return -10;
			}    	     	    	
    } else if (currentResult < lastResult ) {
		
		return 1;	  
	  
	  } else {
		return -1;	  
	  };




};
};

	 
 //  *************Main code*************
    var guessCount = 0;
    var lastGuess =null;
    var getUserGuess = null;
    
     var randNum = Math.floor((Math.random()*100)+1);
     console.log('The random number is ' + randNum);
    $('input#userGuess').focus();    // focus on user text
    
  
     
console.log('At start the last guess is ' + lastGuess);

// refresh page when when users clicks new game button
 $('.new').click(function () {
 	
 	location.reload(); 
 	
 })


// Prevent default page refresh when submit is clicked
$('form').submit(function(event){ 
  			 event.preventDefault(); 
  			
          console.log(guessCount);

})

// get value of user's guess when user clicks guess then compare to random number generated by computer
$('#guessButton').click(function () {
		 
			var getUserGuess = +document.getElementById("userGuess").value;
			var validate = isNaN(getUserGuess);
        	
         if (getUserGuess > 100 ){
         	
         	    $('#feedback').html("You need to select a number between 1 & 100");  
         	    $('input#userGuess').focus(); 
         	
         } else if (validate == true || getUserGuess =="")  {         
       			 
       			      			 
       		 $('#feedback').html("You did not enter a Number.   Please type a number from 1 to 100!");  
         	 $('input#userGuess').focus();
         }  else {	
        	 guessCount++ ;
        	    $('span').html(guessCount);
         var game = new GuessGame (getUserGuess,lastGuess, randNum);
     		var result = game.getResult();
          console.log("This is the result" + result);
          
          switch (result) {
          case 10:          
            $('#feedback').html("You are cold!!!");
            $('#feedback').css("background-color","blue"); 
          break;
          case -10:
            $('#feedback').html("You are hot!!!");
            $('#feedback').css("background-color","red"); 
          break;
          case -1:
            $('#feedback').html("You are colder!!!");
            $('#feedback').css("background-color","blue"); 
          break;
          case 1:
            $('#feedback').html("You are hotter!!!");
            $('#feedback').css("background-color","red"); 
          break;
          case 0:
            $('#feedback').html("You Guessed the Correct Number");
            $('#feedback').css("background-color","green"); 
          }
          
          lastGuess = getUserGuess;
       
          $('input[name="userGuess"').val("");
         
       	 $('ul#guessList').prepend(
 	 			'<li>' + getUserGuess + '</li>'	 	     
 	 			);	
         }
              	 
      
   });

});









